version: "3.10"
   
services:

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Sample_shop_2
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      
volumes:
  postgres_data: