# Generated by Django 4.0.8 on 2023-03-05 22:06

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_UUID',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', auto_created=True, blank=True, editable=False, length=10, max_length=10, null=True, prefix='', unique=True, verbose_name='UUID заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
