# Generated by Django 4.0.8 on 2023-03-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orders_product_list_orders_order_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_info',
            field=models.TextField(blank=True, null=True, verbose_name='Список товаров'),
        ),
    ]
