# Generated by Django 4.0.8 on 2023-03-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_cart_alter_orders_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cart',
            field=models.JSONField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_info',
            field=models.TextField(auto_created=True, blank=True, null=True, verbose_name='Список товаров'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.PositiveIntegerField(auto_created=True, blank=True, null=True),
        ),
    ]
