# Generated by Django 4.0.8 on 2023-04-22 11:23

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orders_cart_alter_orders_order_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_link',
            field=models.URLField(auto_created=True, blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_UUID',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', auto_created=True, length=10, max_length=10, prefix='', unique=True, verbose_name='UUID заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.TextField(blank=True, choices=[('CREATED', 'Платеж создан'), ('WAITING', 'Платёж в обработке / ожидает оплаты'), ('PAID', 'Платёж оплачен'), ('EXPIRED', 'Время жизни счета истекло. Счет не оплачен.'), ('REJECTED', 'Платёж отклонен')], default='CREATED', editable=False, null=True, verbose_name='Статус заказа'),
        ),
    ]
