# Generated by Django 4.0.8 on 2023-06-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orders_payment_link_alter_orders_order_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_UUID',
            new_name='shortuuid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.TextField(blank=True, choices=[('CREATED', 'Платеж создан'), ('WAITING', 'Платёж в обработке / ожидает оплаты'), ('PAID', 'Платёж оплачен'), ('EXPIRED', 'Время жизни счета истекло. Счет не оплачен.'), ('REJECTED', 'Платёж отклонен')], default='CREATED', null=True, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
