# Generated by Django 4.0.8 on 2023-03-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
