# Generated by Django 4.0.8 on 2023-06-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='image',
            field=models.ImageField(default='events_images/placeholder.jpg', upload_to='main_page_slider', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='events_images/placeholder.jpg', upload_to='product_images', verbose_name='Изображение товара'),
        ),
    ]
