# Generated by Django 4.0.6 on 2022-07-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_page_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_image_<built-in function id>')),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
