# Generated by Django 4.0.6 on 2022-07-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_main_page_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_page_slider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='main_page_slider',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
