# Generated by Django 4.0.6 on 2022-08-13 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_products_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='subcategory_id',
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.subcategories'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Shop.categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='information',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
