# Generated by Django 4.0.6 on 2022-08-26 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_remove_products_subcategory_id_products_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('name',), 'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='main_page_slider',
            options={'verbose_name': 'изображение в слайдере', 'verbose_name_plural': 'Изображения в слайдере'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'ordering': ('name',), 'verbose_name': 'подкатегорию', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='add_date',
        ),
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Наличие товара'),
        ),
        migrations.AddField(
            model_name='products',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=10, verbose_name='Остаток товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='main_page_slider',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='main_page_slider',
            name='image',
            field=models.ImageField(upload_to='main_page_slider', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='product_images', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='information',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Краткая информация'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.subcategories', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
    ]
