# Generated by Django 4.0.6 on 2022-08-26 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='main_page_slider',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='add_date',
        ),
        migrations.AddField(
            model_name='categories',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления категории'),
        ),
        migrations.AddField(
            model_name='main_page_slider',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления изображения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_page_slider',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления изображения'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления подкатегории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategories',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления подкатегории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='information',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Краткая информация о товаре'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена товара со скидкой'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.subcategories', verbose_name='Подкатегория товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления товара'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование подкатегории'),
        ),
    ]
