# Generated by Django 4.0.6 on 2022-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_remove_categories_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='available',
            field=models.BooleanField(auto_created=models.PositiveIntegerField(verbose_name='Остаток товара'), default=True, verbose_name='Наличие товара'),
        ),
    ]
