# Generated by Django 4.0.6 on 2022-08-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_alter_products_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='full_information',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Полная информация о товаре'),
        ),
    ]
