# Generated by Django 4.0.6 on 2022-09-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_current_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current_orders',
            old_name='UUID',
            new_name='order_UUID',
        ),
    ]
