# Generated by Django 4.0.6 on 2022-09-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_rename_uuid_current_orders_order_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='current_orders',
        ),
        migrations.AlterField(
            model_name='products',
            name='full_information',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Полная информация о товаре'),
        ),
    ]
