# Generated by Django 4.0.8 on 2022-11-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_alter_products_image_alter_products_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main_page_slider',
            new_name='MainPageSlider',
        ),
    ]
