# Generated by Django 4.0.6 on 2022-09-21 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_UUID',
        ),
        migrations.AddField(
            model_name='orders',
            name='UUID',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
