# Generated by Django 4.0.8 on 2022-10-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_remove_orders_cart_remove_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.JSONField(default={}, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.TextField(choices=[('CREATED', 'Платеж создан'), ('WAITING', 'Платёж в обработке / ожидает оплаты'), ('PAID', 'Платёж оплачен'), ('EXPIRED', 'Время жизни счета истекло. Счет не оплачен.'), ('REJECTED', 'Платёж отклонен')], default='CREATED', verbose_name='Статус заказа'),
        ),
    ]
