# Generated by Django 4.0.8 on 2022-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_orders_cart_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления заказа'),
        ),
    ]
