# Generated by Django 4.1.1 on 2022-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_payment_rename_product_list_orders_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_list',
            field=models.JSONField(default={}, editable=False),
            preserve_default=False,
        ),
    ]
