# Generated by Django 4.1.1 on 2022-10-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_orders_product_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='product_list',
            new_name='order_cart',
        ),
    ]
