# Generated by Django 4.1.1 on 2022-10-07 06:56

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_rename_product_list_orders_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_UUID',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=22, prefix=''),
        ),
    ]
